### ISSUE TITLE
riemann-varnish not working with Varnish 4+

### ISSUE THREAD

**Issue by jamtur01** [aphyr/riemann-tools#104]
Varnish 4.x + has changed the varnishstat command and field names. The new fields should be:

```Ruby
  @vstats = [ "MAIN.sess_conn",
                "MAIN.sess_drop ",
                "MAIN.client_req",
                "MAIN.cache_hit",
                "MAIN.cache_miss" ]
```

I guess we should capture the version output from varnishstat -V and switch on that?

**Comment by aphyr** [comment]
Yeah, I think that's a good plan.
